apiVersion : apps/v1
kind: Deployment
metadata:
  name: "admin-frontend"
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "admin-frontend"
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "admin-frontend"
        dapr.io/app-port: "80"
      labels:
        app: "admin-frontend"
    spec:
      imagePullSecrets:
        - name: containerregistryauth
      containers:
        - name: "admin-frontend"
          image: "lemonsharp.azurecr.io/admin-frontend"
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
